server:
  port: 8081

notary:
  role: REPLICA
  leaderUrl: http://localhost:8080
  replicas:
    - http://localhost:8081
tokens:
  TokenKey: fgsipvfhasrjfshefphasipuefhipuashfiuhaseifhasieuhfiusehfpiahseifhiasuehfipuashefiphaseifhiasehfiuasehfiahsefpihaseipfhasepifhasipuehf
  ValideTime: 600000
  leaderUserName: chuila
ui:
  pageSize: 15
  txPerBlock: 5

spring:
  datasource:
    url: jdbc:sqlite:./replica.db
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

