server:
  port: 8081

notary:
  role: REPLICA
  leaderUrl: http://localhost:8080

spring:
  datasource:
    url: jdbc:sqlite:./notary-replica.db
    driver-class-name: org.sqlite.JDBC

  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
